// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharedTrip.Infrastructure.Data;

#nullable disable

namespace SharedTrip.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221122134123_AddedIsDeleted")]
    partial class AddedIsDeleted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountOfTripsAsDriver")
                        .HasColumnType("int");

                    b.Property<int>("CountOfTripsAsPassenger")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abarth"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bentley"
                        },
                        new
                        {
                            Id = 6,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bugatti"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cadillac"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Chrysler"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Citroën"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dacia"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Daewoo"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Daihatsu"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Dodge"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Donkervoort"
                        },
                        new
                        {
                            Id = 17,
                            Name = "DS"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Fisker"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Hummer"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Infiniti"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Iveco"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 30,
                            Name = "KTM"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Lada"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Lancia"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Landwind"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Lotus"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Maserati"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Maybach"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 41,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 43,
                            Name = "MG"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Mini"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Morgan"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Opel"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Rolls-Royce"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Rover"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Saab"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Seat"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Skoda"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Smart"
                        },
                        new
                        {
                            Id = 58,
                            Name = "SsangYong"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Volvo"
                        });
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("Climatronic")
                        .HasColumnType("bit");

                    b.Property<int>("ColourId")
                        .HasColumnType("int");

                    b.Property<int>("CountOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColourId");

                    b.HasIndex("DriverId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Colours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Син"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Червен"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Черен"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Бял"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Сив"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Жълт"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Кафяв"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Зелен"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Лилав"
                        });
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.PassengerTrip", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("PassengerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TripId", "PassengerId");

                    b.HasIndex("PassengerId");

                    b.ToTable("PassengersTrips");
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.PopulatedPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("PopulatedPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Банско"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Белица"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Благоевград"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Гоце Делчев"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Гърмен"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Кресна"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Петрич"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Разлог"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Сандански"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Сатовча"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Симитли"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Струмяни"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Хаджидимово"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Якоруда"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Айтос"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Бургас"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Камено"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Карнобат"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Малко Търново"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Несебър"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Поморие"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Приморско"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Руен"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Созопол"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Средец"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Сунгурларе"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Царево"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Варна"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Аврен"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Аксаково"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Белослав"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Бяла"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Варна"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Ветрино"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Вълчи дол"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Девня"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Долни чифлик"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Дългопол"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Провадия"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Суворово"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Велико Търново"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Велико Търново"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Горна Оряховица"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Елена"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Златарица"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Лясковец"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Павликени"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Полски Тръмбеш"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Свищов"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Стражица"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Сухиндол"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Видин"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Белоградчик"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Бойница"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Брегово"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Видин"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Грамада"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Димово"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Кула"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Макреш"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Ново село"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Ружинци"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Чупрене"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Враца"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Борован"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Бяла Слатина"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Враца"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Козлодуй"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Криводол"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Мездра"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Мизия"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Оряхово"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Роман"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Хайредин"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Габрово"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Габрово"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Дряново"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Севлиево"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Трявна"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Добрич/Толбухин"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Балчик"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Генерал Тошево"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Добрич-селска"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Добрич"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Каварна"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Крушари"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Тервел"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Шабла"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Кърджали"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Ардино"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Джебел"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Кирково"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Крумовград"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Кърджали"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Момчилград"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Черноочене"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Кюстендил"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Бобов дол"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Бобошево"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Дупница"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Кочериново"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Кюстендил"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Невестино"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Рила"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Сапарева баня"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Трекляно"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Ловеч"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Априлци"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Летница"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Ловеч"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Луковит"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Тетевен"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Троян"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Угърчин"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Ябланица"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Монтана"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Берковица"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Бойчиновци"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Брусарци"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Вълчедръм"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Вършец"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Георги Дамяново"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Лом"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Медковец"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Монтана"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Чипровци"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Якимово"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Пазарджик"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Батак"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Белово"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Брацигово"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Велинград"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Лесичово"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Пазарджик"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Панагюрище"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Пещера"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Ракитово"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Септември"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Стрелча"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Сърница"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Перник"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Брезник"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Земен"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Ковачевци"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Перник"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Радомир"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Трън"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Плевен"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Белене"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Гулянци"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Долна Митрополия"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Долни Дъбник"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Искър"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Кнежа"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Левски"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Никопол"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Плевен"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Пордим"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Червен бряг"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Пловдив"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Асеновград"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Брезово"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Калояново"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Карлово"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Кричим"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Куклен"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Лъки"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Марица"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Перущица"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Пловдив"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Първомай"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Раковски"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Родопи"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Садово"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Сопот"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Стамболийски"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Съединение"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Хисаря"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Разград"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Завет"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Исперих"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Кубрат"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Лозница"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Разград"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Самуил"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Цар Калоян"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Русе"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Борово"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Бяла"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Ветово"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Две могили"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Иваново"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Русе"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Сливо поле"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Ценово"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Силистра"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Алфатар"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Главиница"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Дулово"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Кайнарджа"
                        },
                        new
                        {
                            Id = 201,
                            Name = "Силистра"
                        },
                        new
                        {
                            Id = 202,
                            Name = "Ситово"
                        },
                        new
                        {
                            Id = 203,
                            Name = "Тутракан"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Сливен"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Котел"
                        },
                        new
                        {
                            Id = 206,
                            Name = "Нова Загора"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Сливен"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Твърдица"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Смолян"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Баните"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Борино"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Девин"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Доспат"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Златоград"
                        },
                        new
                        {
                            Id = 215,
                            Name = "Мадан"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Неделино"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Рудозем"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Смолян"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Чепеларе"
                        },
                        new
                        {
                            Id = 220,
                            Name = "София"
                        },
                        new
                        {
                            Id = 221,
                            Name = "Антон"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Божурище"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Ботевград"
                        },
                        new
                        {
                            Id = 224,
                            Name = "Годеч"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Горна Малина"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Долна баня"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Драгоман"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Елин Пелин"
                        },
                        new
                        {
                            Id = 229,
                            Name = "Етрополе"
                        },
                        new
                        {
                            Id = 230,
                            Name = "Златица"
                        },
                        new
                        {
                            Id = 231,
                            Name = "Ихтиман"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Копривщица"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Костенец"
                        },
                        new
                        {
                            Id = 234,
                            Name = "Костинброд"
                        },
                        new
                        {
                            Id = 235,
                            Name = "Мирково"
                        },
                        new
                        {
                            Id = 236,
                            Name = "Пирдоп"
                        },
                        new
                        {
                            Id = 237,
                            Name = "Правец"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Самоков"
                        },
                        new
                        {
                            Id = 239,
                            Name = "Своге"
                        },
                        new
                        {
                            Id = 240,
                            Name = "Сливница"
                        },
                        new
                        {
                            Id = 241,
                            Name = "Чавдар"
                        },
                        new
                        {
                            Id = 242,
                            Name = "Челопеч"
                        },
                        new
                        {
                            Id = 243,
                            Name = "Стара Загора"
                        },
                        new
                        {
                            Id = 244,
                            Name = "Братя Даскалови"
                        },
                        new
                        {
                            Id = 245,
                            Name = "Гурково"
                        },
                        new
                        {
                            Id = 246,
                            Name = "Гълъбово"
                        },
                        new
                        {
                            Id = 247,
                            Name = "Казанлък"
                        },
                        new
                        {
                            Id = 248,
                            Name = "Мъглиж"
                        },
                        new
                        {
                            Id = 249,
                            Name = "Николаево"
                        },
                        new
                        {
                            Id = 250,
                            Name = "Опан"
                        },
                        new
                        {
                            Id = 251,
                            Name = "Павел баня"
                        },
                        new
                        {
                            Id = 252,
                            Name = "Раднево"
                        },
                        new
                        {
                            Id = 253,
                            Name = "Стара Загора"
                        },
                        new
                        {
                            Id = 254,
                            Name = "Чирпан"
                        },
                        new
                        {
                            Id = 255,
                            Name = "Търговище"
                        },
                        new
                        {
                            Id = 256,
                            Name = "Антоново"
                        },
                        new
                        {
                            Id = 257,
                            Name = "Омуртаг"
                        },
                        new
                        {
                            Id = 258,
                            Name = "Опака"
                        },
                        new
                        {
                            Id = 259,
                            Name = "Попово"
                        },
                        new
                        {
                            Id = 260,
                            Name = "Търговище"
                        },
                        new
                        {
                            Id = 261,
                            Name = "Хасково"
                        },
                        new
                        {
                            Id = 262,
                            Name = "Димитровград"
                        },
                        new
                        {
                            Id = 263,
                            Name = "Ивайловград"
                        },
                        new
                        {
                            Id = 264,
                            Name = "Любимец"
                        },
                        new
                        {
                            Id = 265,
                            Name = "Маджарово"
                        },
                        new
                        {
                            Id = 266,
                            Name = "Минерални бани"
                        },
                        new
                        {
                            Id = 267,
                            Name = "Свиленград"
                        },
                        new
                        {
                            Id = 268,
                            Name = "Симеоновград"
                        },
                        new
                        {
                            Id = 269,
                            Name = "Стамболово"
                        },
                        new
                        {
                            Id = 270,
                            Name = "Тополовград"
                        },
                        new
                        {
                            Id = 271,
                            Name = "Харманли"
                        },
                        new
                        {
                            Id = 272,
                            Name = "Хасково"
                        },
                        new
                        {
                            Id = 273,
                            Name = "Шумен"
                        },
                        new
                        {
                            Id = 274,
                            Name = "Велики Преслав"
                        },
                        new
                        {
                            Id = 275,
                            Name = "Венец"
                        },
                        new
                        {
                            Id = 276,
                            Name = "Върбица"
                        },
                        new
                        {
                            Id = 277,
                            Name = "Каолиново"
                        },
                        new
                        {
                            Id = 278,
                            Name = "Каспичан"
                        },
                        new
                        {
                            Id = 279,
                            Name = "Никола Козлево"
                        },
                        new
                        {
                            Id = 280,
                            Name = "Нови пазар"
                        },
                        new
                        {
                            Id = 281,
                            Name = "Смядово"
                        },
                        new
                        {
                            Id = 282,
                            Name = "Хитрино"
                        },
                        new
                        {
                            Id = 283,
                            Name = "Шумен"
                        },
                        new
                        {
                            Id = 284,
                            Name = "Ямбол"
                        },
                        new
                        {
                            Id = 285,
                            Name = "Болярово"
                        },
                        new
                        {
                            Id = 286,
                            Name = "Елхово"
                        },
                        new
                        {
                            Id = 287,
                            Name = "Стралджа"
                        },
                        new
                        {
                            Id = 288,
                            Name = "Тунджа"
                        },
                        new
                        {
                            Id = 289,
                            Name = "Ямбол"
                        });
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AllowedBaverages")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowedFood")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowedSmoking")
                        .HasColumnType("bit");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CountOfSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EndDestinationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SpaceForLuggage")
                        .HasColumnType("bit");

                    b.Property<int>("StartDestinationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId");

                    b.HasIndex("EndDestinationId");

                    b.HasIndex("StartDestinationId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Car", b =>
                {
                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.Colour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", "Driver")
                        .WithMany("Cars")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Colour");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Comment", b =>
                {
                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", "Receiver")
                        .WithMany("ReceivedComments")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Message", b =>
                {
                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.PassengerTrip", b =>
                {
                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", "Passenger")
                        .WithMany("PassengersTrips")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.Trip", "Trip")
                        .WithMany("PassengersTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Trip", b =>
                {
                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", "Driver")
                        .WithMany("DriverTrips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.PopulatedPlace", "EndDestination")
                        .WithMany()
                        .HasForeignKey("EndDestinationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SharedTrip.Infrastructure.Data.Entities.PopulatedPlace", "StartDestination")
                        .WithMany()
                        .HasForeignKey("StartDestinationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Driver");

                    b.Navigation("EndDestination");

                    b.Navigation("StartDestination");
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("DriverTrips");

                    b.Navigation("PassengersTrips");

                    b.Navigation("ReceivedComments");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("SharedTrip.Infrastructure.Data.Entities.Trip", b =>
                {
                    b.Navigation("PassengersTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
